version: '3'

services:
  server:
    container_name: one-health-server
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "8080:8080"
    networks:
      - one-health-network
    depends_on:
      - graphdb

  client:
    container_name: one-health-client
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - "3000:80"
    networks:
      - one-health-network
    depends_on:
      - server

  graphdb:
    container_name: one-health-graphdb
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - one-health-network
    volumes:
      - /data/onehealth/data:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

networks:
  one-health-network:
    driver: bridge