

version: '3'

services:
  graphdb:
    container_name: one-health-graphdb
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - sources_cu_plants_ontology_data:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

  postgredb:
    container_name: one-health-postgredb
    image: postgres_rdkit
    ports:
      - "5433:5432"
    volumes:
      -  one_health_postgredb_data:/data
    environment:
      POSTGRES_USER: one_healt_huser
      POSTGRES_PASSWORD: one_health_password
      POSTGRES_DB: one_health

volumes:
  sources_cu_plants_ontology_data:
    external: true
  
  one_health_postgredb_data: