

version: '3'

services:
  graphdb:
    container_name: one-health-graphdb
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - sources_cu_plants_ontology_data:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

volumes:
  sources_cu_plants_ontology_data:
    external: true