#
# Copyright 2025 Leibniz-Institut f. Pflanzenbiochemie
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
version: '3'

services:
  server:
    container_name: one-health-server
    build:
      context: .
      dockerfile: ./docker/server/server.Dockerfile
    # TODO: expose for debuging purposes only 
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    depends_on:
      postgredb:
          condition: service_healthy  # ensures the correct start of postgredb
      graphdb:
          condition: service_healthy

  client:
    container_name: one-health-client
    build:
      context: .
      dockerfile: ./docker/client/client.Dockerfile
    ports:
      - "80:80"
    hostname: www.example.com
    networks:
      - frontend
    volumes:
      - /srv/www/conf:/usr/local/apache2/conf
      - /srv/www/letsencrypt/.well-known:/usr/local/apache2/htdocs/.well-known
    depends_on:
      - server

  graphdb:
    container_name: one-health-graphdb
    image: neo4j
    # expose graphdb ports for debugging only
    ports:
     - "7474:7474"
     - "7687:7687" # for BOLT-Protocol
    networks:
      - backend
    volumes:
      - n4j_data:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:7474"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  postgredb:
    container_name: one-health-postgredb
    build:
      context: .
      dockerfile: ./docker/rdkit/rdkit.Dockerfile
    # expose database port for debugging only
    # ports:
    #  - "5432:5433"
    networks:
      - backend
    volumes:
      -  pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: one_healt_huser
      POSTGRES_PASSWORD: one_health_password
      POSTGRES_DB: one_health
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U one_healt_huser -d one_health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  frontend:
  backend:

volumes:
  pg_data:
  n4j_data:
