spring.application.name=curator

spring.datasource.url=jdbc:postgresql://localhost:5432/curator
spring.datasource.username=curator
spring.datasource.password=curator
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=true 

