spring.neo4j.uri=bolt://graphdb:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password


spring.datasource.url=jdbc:postgresql://postgredb:5432/one_health
spring.datasource.username=one_health_user
spring.datasource.password=one_health_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true 

logging.level.org.springframework.data.neo4j.cypher.deprecation=OFF
logging.level.org.springframework.data.neo4j.cypher.unrecognized=OFF


spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1600000
spring.datasource.hikari.leak-detection-threshold=10000


spring.security.oauth2.client.registration.orcid.provider=orcid
spring.security.oauth2.client.registration.orcid.client-id=${ORCID_CLIENT_ID}
spring.security.oauth2.client.registration.orcid.client-secret=${ORCID_CLIENT_SECRET}
spring.security.oauth2.client.registration.orcid.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.orcid.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.orcid.scope=openid
spring.security.oauth2.client.registration.orcid.redirect-uri=${ORCID_REDIRECT_URI:{baseUrl}/api/login/oauth2/code/{registrationId}}

spring.security.oauth2.client.provider.orcid.issuer-uri=https://orcid.org


server.forward-headers-strategy=framework