/*
 * Curator database setup
 */
\set CURATOR_DATABASE curator
\set CURATOR_SCHEMA curator
\set CURATOR_USER curator
\set CURATOR_PW curator

-- quoted variables --
\set CURATOR_PW_QUOTED '\'' :CURATOR_PW '\''
\set CURATOR_DATABASE_QUOTED '\'' :CURATOR_DATABASE '\''

-- terminate active sessions --
SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE pg_stat_activity.datname = :CURATOR_DATABASE_QUOTED
  AND pid <> pg_backend_pid();

-- cleanup --
DROP SCHEMA IF EXISTS :CURATOR_SCHEMA CASCADE;
DROP DATABASE IF EXISTS :CURATOR_DATABASE;
DROP USER IF EXISTS :CURATOR_USER;

-- creation --
CREATE USER :CURATOR_USER PASSWORD :CURATOR_PW_QUOTED;
CREATE DATABASE :CURATOR_DATABASE WITH ENCODING 'UTF8' OWNER :CURATOR_USER;

\connect :CURATOR_DATABASE

-- schema --
CREATE SCHEMA AUTHORIZATION :CURATOR_USER;

-- adjust schema search path --
ALTER USER :CURATOR_USER SET search_path to :CURATOR_SCHEMA,public;

-- privileges --
GRANT USAGE ON SCHEMA :CURATOR_SCHEMA, public TO :CURATOR_USER;
GRANT CONNECT, TEMPORARY, TEMP  ON  DATABASE :CURATOR_DATABASE to :CURATOR_USER;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA :CURATOR_SCHEMA to :CURATOR_USER;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public to :CURATOR_USER;
REVOKE ALL ON ALL TABLES IN SCHEMA :CURATOR_SCHEMA FROM public;

-- check for usefull extensions and install it --
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

\i schema/0001_onehealth.sql
