name: continuous-integration-test

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0
    - name: Install Node.js dependencies
      run: cd ontology-manager-client && npm install
    - name: Audit Node.js dependencies
      run: cd ontology-manager-client && npm audit --omit=dev
